version: '3.8'

services:
  gaa-scraper:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:WAHiuVCRoxTQsKfyNUNkEAXnSNZRAnjS@centerbeam.proxy.rlwy.net:28138/railway
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Add a backup service for automated data backups
  gaa-backup:
    build: .
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    command: npm run backup
    profiles:
      - backup
    restart: "no" 